title: PS2Tek
lang: en
markdown: GFM
description: Write an awesome description for your new site here

remote_theme: JV-conseil/jekyll-theme-read-the-docs

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
